import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import SwitchTheme from "./components/SwitchTheme";
import { ThemeProvider } from "next-themes";
import Link from "next/link";
import {
  Braces,
  Code,
  Command,
  Hexagon,
  SquareActivity,
  SquareCode,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Top() {
  return (
    <Link href="/" className="flex gap-1 items-center ">
      <Command className="size-6" />
    </Link>
  );
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    /* documented way to supress the hydration warning(i think)*/
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="flex justify-between p-4 sticky top-0 z-20 bg-background border-b border-border/60">
            <Top />
            <div className="flex gap-2 items-center justify-center">
              <SwitchTheme />
              <Navbar />
            </div>
          </header>
          <div className="mt-6 p-6"> {children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
